version: '3.8'
services:
  minio:
    image: bitnami/minio:2022
    container_name: minio
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_DEFAULT_BUCKETS: 202301-urfu-rtf
    ports:
      - "9000:9000"
      - "9001:9001"

  mutual-marker-back:
    container_name: mutual-marker-back
    build:
      context: .
    image: mutual-marker-back:latest
    ports:
      - "8090:8080"
    depends_on:
      - psql
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql:5432/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FILE_STORAGE: ${FILE_STORAGE}
      MINIO_URL: http://minio:9000
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MAX_FILE_SIZE: 20MB
      MAX_REQUEST_SIZE: 20MB
      FILE-SIZE-THRESHOLD: 2KB

  psql:
    image: 'postgres:13.1-alpine'
    container_name: psql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1976:5432"

#  mutual-marker-front:
#    container_name: mutual-marker-front
#    build:
#      context: ../mutual-marker-front/.
#    image: mutual-marker-front:latest
#    volumes:
#      - '.:/main'
#      - '/main/node_modules'
#    ports:
#      - "80:80"