version: '3.8'
services:
  minio:
    image: bitnami/minio:2021.3.1
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_DEFAULT_BUCKETS: 202301-urfu-rtf
    ports:
      - 9000:9000
  mutual-marker-back:
    container_name: mutual-marker-back
    build:
      context: .
    image: mutual-marker-back:latest
    ports:
      - "8090:8080"
    depends_on:
      - psql
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FILE_STORAGE: ../mutual-marker
      MINIO_URL: http://minio:9000
      MINIO_BUCKET: 202301-urfu-rtf
      MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SECRET_KEY: tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      MAX_FILE_SIZE: 20MB
      MAX_REQUEST_SIZE: 20MB
      FILE-SIZE-THRESHOLD: 2KB

  psql:
    image: 'postgres:13.1-alpine'
    container_name: psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"