
spring:
  application:
    name: mutual-marker
    schema: mutual_marker
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driverClassName:
  flyway:
    baseline-on-migrate: true
    schemas: ${spring.application.schema}
  jpa:
      properties:
        hibernate:
          dialect=org:
            hibernate:
              dialect:
                PostgreSQL10Dialect
