
spring:
  application:
    name: mutual-marker
    schema: mutual_marker
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName:
  flyway:
    baseline-on-migrate: true
    schemas: ${spring.application.schema}
  jpa:
    properties:
        hibernate:
          dialect=org:
            hibernate:
              dialect:
                PostgreSQL10Dialect

springdoc:
  api-docs:
    path: /api-docs