
spring:
  application:
    name: mutual-marker
    schema: mutual_marker
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName:
  flyway:
    baseline-on-migrate: true
    schemas: ${spring.application.schema}
  jpa:
    properties:
        hibernate:
          ddl-auto: update
          dialect=org:
            hibernate:
              dialect:
                PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
