spring:
  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 300MB
  application:
    name: mutual-marker
    schema: mutual_marker
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    baseline-on-migrate: true
    schemas: ${spring.application.schema}
  jpa:
    properties:
        hibernate:
          dialect=org:
            hibernate:
              dialect:
                PostgreSQL10Dialect
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  minio:
    bucket: ${MINIO_BUCKET:file-storage}
    url: ${MINIO_URL:http://127.0.0.1:9000}
    access-key: ${MINIO_ACCESS_KEY:user}
    secret-key: ${MINIO_SECRET_KEY:password}


springdoc:
  api-docs:
    path: /api-docs


mutual-marker:
  filepath: ${FILE_STORAGE}